-- Maeven CRM Core Schema Definition
-- Designed to be brand-agnostic but optimized for modern retail analytics.
-- Custom and brand-specific attributes are handled via Postgres JSONB and tags.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 1. CUSTOMERS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS customers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT UNIQUE NOT NULL,
    city TEXT,
    age INTEGER,
    gender TEXT,
    tags TEXT[] DEFAULT '{}',
    attributes JSONB DEFAULT '{}',
    total_orders INTEGER DEFAULT 0,
    total_spent NUMERIC(12, 2) DEFAULT 0.00,
    last_purchase_date TIMESTAMP WITH TIME ZONE,
    dormancy_status TEXT DEFAULT 'active', -- active, at_risk, dormant
    rfm_score INTEGER,
    rfm_segment TEXT, -- Champions, Loyal, About to Sleep, Lost, etc.
    churn_risk NUMERIC(5, 2) DEFAULT 0.00, -- Probability 0 to 100
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- =========================================================================
-- 2. PRODUCTS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    subcategory TEXT,
    tags TEXT[] DEFAULT '{}',
    attributes JSONB DEFAULT '{}',
    price NUMERIC(12, 2) NOT NULL,
    collection_name TEXT,
    is_limited BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- =========================================================================
-- 3. ORDERS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID REFERENCES customers(id) ON DELETE CASCADE NOT NULL,
    items JSONB NOT NULL DEFAULT '[]', -- Array of {product_id, name, price, quantity}
    order_value NUMERIC(12, 2) NOT NULL,
    gifting_flag BOOLEAN DEFAULT FALSE,
    occasion_tag TEXT,
    order_channel TEXT NOT NULL, -- website, retail_store, whatsapp, instagram
    order_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- =========================================================================
-- 4. SEGMENTS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS segments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    filter_json JSONB NOT NULL DEFAULT '{}', -- Raw logical rules for filtering
    nl_query TEXT, -- Natural language description of the query
    customer_count INTEGER DEFAULT 0,
    created_by UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- =========================================================================
-- 5. CAMPAIGNS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS campaigns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    segment_id UUID REFERENCES segments(id) ON DELETE SET NULL,
    channel TEXT NOT NULL, -- email, sms, whatsapp
    message_template TEXT NOT NULL,
    goal TEXT,
    status TEXT DEFAULT 'draft' NOT NULL, -- draft, scheduled, processing, completed, failed
    ai_insight TEXT, -- Dynamic insights generated by Grok
    total_recipients INTEGER DEFAULT 0,
    sent_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- =========================================================================
-- 6. COMMUNICATIONS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS communications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    campaign_id UUID REFERENCES campaigns(id) ON DELETE CASCADE NOT NULL,
    customer_id UUID REFERENCES customers(id) ON DELETE CASCADE NOT NULL,
    message_body TEXT NOT NULL,
    channel TEXT NOT NULL,
    status TEXT DEFAULT 'queued' NOT NULL, -- queued, sent, delivered, failed, opened, read, clicked
    queued_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    delivered_at TIMESTAMP WITH TIME ZONE,
    failed_at TIMESTAMP WITH TIME ZONE,
    opened_at TIMESTAMP WITH TIME ZONE,
    read_at TIMESTAMP WITH TIME ZONE,
    clicked_at TIMESTAMP WITH TIME ZONE
);

-- =========================================================================
-- 7. CAMPAIGN STATS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS campaign_stats (
    campaign_id UUID PRIMARY KEY REFERENCES campaigns(id) ON DELETE CASCADE,
    total_sent INTEGER DEFAULT 0 NOT NULL,
    delivered INTEGER DEFAULT 0 NOT NULL,
    failed INTEGER DEFAULT 0 NOT NULL,
    opened INTEGER DEFAULT 0 NOT NULL,
    read_count INTEGER DEFAULT 0 NOT NULL,
    clicked INTEGER DEFAULT 0 NOT NULL,
    delivery_rate NUMERIC(5, 2) DEFAULT 0.00 NOT NULL,
    open_rate NUMERIC(5, 2) DEFAULT 0.00 NOT NULL,
    click_rate NUMERIC(5, 2) DEFAULT 0.00 NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- =========================================================================
-- INDEXES FOR PERFORMANCE
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers(email);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone);
CREATE INDEX IF NOT EXISTS idx_customers_rfm ON customers(rfm_segment);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_date ON orders(order_date);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category, subcategory);
CREATE INDEX IF NOT EXISTS idx_campaigns_segment ON campaigns(segment_id);
CREATE INDEX IF NOT EXISTS idx_communications_campaign ON communications(campaign_id);
CREATE INDEX IF NOT EXISTS idx_communications_customer ON communications(customer_id);
CREATE INDEX IF NOT EXISTS idx_communications_status ON communications(status);

-- =========================================================================
-- POSTGRES RPC: increment_campaign_stat
-- Safely increments a metric field and recomputes the rate metrics atomically.
-- =========================================================================
CREATE OR REPLACE FUNCTION increment_campaign_stat(
  p_campaign_id UUID,
  p_field TEXT
) RETURNS VOID AS $$
BEGIN
  INSERT INTO campaign_stats (
    campaign_id,
    total_sent,
    delivered,
    failed,
    opened,
    read_count,
    clicked,
    delivery_rate,
    open_rate,
    click_rate,
    updated_at
  ) VALUES (
    p_campaign_id,
    CASE WHEN p_field = 'total_sent' THEN 1 ELSE 0 END,
    CASE WHEN p_field = 'delivered' THEN 1 ELSE 0 END,
    CASE WHEN p_field = 'failed' THEN 1 ELSE 0 END,
    CASE WHEN p_field = 'opened' THEN 1 ELSE 0 END,
    CASE WHEN p_field = 'read_count' THEN 1 ELSE 0 END,
    CASE WHEN p_field = 'clicked' THEN 1 ELSE 0 END,
    0.00, 0.00, 0.00,
    timezone('utc', now())
  )
  ON CONFLICT (campaign_id) DO UPDATE SET
    total_sent = campaign_stats.total_sent + CASE WHEN p_field = 'total_sent' THEN 1 ELSE 0 END,
    delivered = campaign_stats.delivered + CASE WHEN p_field = 'delivered' THEN 1 ELSE 0 END,
    failed = campaign_stats.failed + CASE WHEN p_field = 'failed' THEN 1 ELSE 0 END,
    opened = campaign_stats.opened + CASE WHEN p_field = 'opened' THEN 1 ELSE 0 END,
    read_count = campaign_stats.read_count + CASE WHEN p_field = 'read_count' THEN 1 ELSE 0 END,
    clicked = campaign_stats.clicked + CASE WHEN p_field = 'clicked' THEN 1 ELSE 0 END,
    updated_at = timezone('utc', now());

  -- Recompute rates (Rates are computed relative to total_sent or delivered, depending on metric definition)
  -- 1. Delivery rate = (delivered / total_sent) * 100
  -- 2. Open rate = (opened / total_sent) * 100
  -- 3. Click rate = (clicked / total_sent) * 100
  UPDATE campaign_stats
  SET 
    delivery_rate = CASE 
      WHEN total_sent > 0 THEN ROUND((delivered::numeric / total_sent::numeric) * 100, 2)
      ELSE 0.00 
    END,
    open_rate = CASE 
      WHEN total_sent > 0 THEN ROUND((opened::numeric / total_sent::numeric) * 100, 2)
      ELSE 0.00 
    END,
    click_rate = CASE 
      WHEN total_sent > 0 THEN ROUND((clicked::numeric / total_sent::numeric) * 100, 2)
      ELSE 0.00 
    END
  WHERE campaign_id = p_campaign_id;
END;
$$ LANGUAGE plpgsql;

-- =========================================================================
-- SUPABASE REALTIME CONFIGURATION
-- =========================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END $$;

-- Check and add tables to publication safely
DO $$
BEGIN
  -- We add the tables if they aren't already part of the publication
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'communications'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE communications;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'campaign_stats'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE campaign_stats;
  END IF;
END $$;


-- =========================================================================
-- 8. DEALS TABLE (KANBAN SALES AUTOMATION)
-- =========================================================================
CREATE TABLE IF NOT EXISTS deals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID REFERENCES customers(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    value NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    stage TEXT NOT NULL CHECK (stage IN ('prospect', 'qualified', 'proposal', 'negotiation', 'closed_won', 'closed_lost')),
    expected_close_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_deals_customer ON deals(customer_id);
CREATE INDEX IF NOT EXISTS idx_deals_stage ON deals(stage);

-- Add deals to Supabase Realtime publication
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'deals'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE deals;
  END IF;
END $$;


-- =========================================================================
-- 9. TICKETS TABLE (SHARED SUPPORT INBOX)
-- =========================================================================
CREATE TABLE IF NOT EXISTS tickets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id UUID REFERENCES customers(id) ON DELETE CASCADE NOT NULL,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('open', 'pending', 'resolved')),
    priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_tickets_customer ON tickets(customer_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status);
CREATE INDEX IF NOT EXISTS idx_tickets_priority ON tickets(priority);

-- Add tickets to Supabase Realtime publication
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables 
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'tickets'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE tickets;
  END IF;
END $$;

