import { Sparkles, TrendingUp, AlertTriangle, ArrowRight } from "lucide-react";

export default function InsightsPage() {
  const recommendations = [
    {
      id: "rec-1",
      title: "Elevate 'Oxidised Heritage' Campaign Frequency",
      description: "Our customer response rates for oxidised jewelry pieces show a 34% uptick in click rates when delivered via WhatsApp rather than standard SMS, particularly for customers aged 25-35 in Bangalore.",
      type: "opportunity",
      metric: "+34% Click rate"
    },
    {
      id: "rec-2",
      title: "Urgent: Churn Alert on 'About to Sleep' Segment",
      description: "Average days since last purchase for the 'About to Sleep' segment has increased from 110 days to 142 days in the last month. Suggest triggering a winback offering stackable silver ring bundles.",
      type: "critical",
      metric: "High Churn Risk"
    },
    {
      id: "rec-3",
      title: "Optimise Gifting-Heavy templates for Anniversaries",
      description: "Customers tagging their purchases as 'Anniversary' order with a 40% higher average order value. Personalizing email templates with custom gift wrapping offers before their anniversary date increases conversion.",
      type: "info",
      metric: "40% Higher AOV"
    }
  ];

  return (
    <div className="space-y-8 max-w-7xl w-full mx-auto">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-serif font-bold tracking-wide text-foreground">
          AI Insights Console
        </h1>
        <p className="text-sm text-muted">
          Dynamic optimization suggestions generated by Grok-beta using database metrics.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Column: Main Recommendations Feed */}
        <div className="lg:col-span-2 space-y-6">
          <h2 className="text-xl font-serif font-semibold text-foreground">
            Actionable Recommendations
          </h2>

          <div className="space-y-4">
            {recommendations.map((rec) => (
              <div 
                key={rec.id} 
                className={`premium-card border-l-4 flex flex-col gap-4 ${
                  rec.type === "critical"
                    ? "border-l-amber-500/80 bg-gradient-to-r from-[#14100e] to-card"
                    : rec.type === "opportunity"
                    ? "border-l-primary/80 bg-gradient-to-r from-[#11120f] to-card"
                    : "border-l-[#54607a]/80 bg-gradient-to-r from-[#0d0f14] to-card"
                }`}
              >
                <div className="flex justify-between items-start gap-4">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      {rec.type === "critical" ? (
                        <AlertTriangle className="w-4 h-4 text-amber-500" />
                      ) : (
                        <Sparkles className="w-4 h-4 text-primary" />
                      )}
                      <h3 className="font-semibold text-sm text-foreground">
                        {rec.title}
                      </h3>
                    </div>
                    <p className="text-xs text-muted leading-relaxed">
                      {rec.description}
                    </p>
                  </div>
                  <span className={`text-[10px] font-semibold font-mono uppercase tracking-wider px-2 py-0.5 rounded border whitespace-nowrap ${
                    rec.type === "critical"
                      ? "bg-amber-500/10 text-amber-500 border-amber-500/20"
                      : "bg-primary/10 text-primary border-primary/20"
                  }`}>
                    {rec.metric}
                  </span>
                </div>

                <div className="flex justify-end pt-2 border-t border-border/40">
                  <button className="text-xs text-primary hover:text-primary-hover font-semibold flex items-center gap-1 transition-colors">
                    <span>Apply Optimization</span>
                    <ArrowRight className="w-3 h-3" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Right Column: Analytics Insights Summary */}
        <div className="space-y-6">
          <h2 className="text-xl font-serif font-semibold text-foreground">
            Audience Trends
          </h2>

          <div className="premium-card flex flex-col gap-5">
            <h3 className="font-serif font-semibold text-primary text-sm flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-primary" />
              <span>Grok Growth Report</span>
            </h3>

            <p className="text-xs text-muted leading-normal">
              Based on transactions over the past 30 days, jewelry category preferences have shifted towards <strong>Sterling Silver</strong> items (up 18.4%), while gold-plated orders are seeing stable growth.
            </p>

            <div className="border border-border p-4 rounded-lg bg-[#070709] space-y-3">
              <span className="text-[10px] font-bold text-muted uppercase tracking-wider block">
                Top Jewelry Collections
              </span>
              <div className="space-y-2 text-xs">
                {[
                  { name: "Minimalist Chic", sales: "$4,200 spent", percentage: 48 },
                  { name: "Oxidised Heritage", sales: "$3,100 spent", percentage: 32 },
                  { name: "Floral Bloom", sales: "$1,850 spent", percentage: 20 }
                ].map((item) => (
                  <div key={item.name} className="space-y-1">
                    <div className="flex justify-between font-medium">
                      <span>{item.name}</span>
                      <span className="text-muted">{item.sales}</span>
                    </div>
                    <div className="w-full h-1 bg-[#121217] rounded-full overflow-hidden">
                      <div className="h-full bg-primary" style={{ width: `${item.percentage}%` }} />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
